# nacos配置
nacos:
  server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  username: ${NACOS_USERNAME:nacos}
  password: ${NACOS_PASSWORD:nacos}
  namespace: ${NACOS_NAMESPACE:dev-namespace}
  config:
    group: ${NACOS_CONFIG_GROUP:SERVER}
  discovery:
    group: ${NACOS_DISCOVERY_GROUP:dev}
    cluster-name: ${NACOS_DISCOVERY_CLUSTER:master}


spring:
  application:
    name: ${APPLICATION_NAME:wd-file-center}
  profiles:
    active: ${APPLICATION_PROFILE:dev}
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.config.group}
        file-extension: yml
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.discovery.group}
        cluster-name: ${nacos.discovery.cluster-name}
  config:
    import:
      - nacos:wd-file-center.yml
      - optional:nacos:wd-common.yml?group=COMMON&refreshEnabled=true
      - optional:nacos:wd-common-redis.yml?group=COMMON&refreshEnabled=false

logging:
  file:
    path: /Users/huangwenda/logs/wd-cloud
    name: ${spring.application.name}

dubbo:
  application:
    name: ${spring.application.name}-provider
    logger: slf4j
    # 元数据中心 local 本地 remote 远程
    metadata-type: remote
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
    service-discovery:
      # FORCE_INTERFACE，只消费接口级地址 FORCE_APPLICATION，只消费应用级地址 APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
      migration: FORCE_APPLICATION
    qos-port: 22222
  protocol:
    name: tri
    port: -1
    prefer-serialization: fastjson2
  # 注册中心配置
  registry:
    address: nacos://${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
    parameters:
      namespace: ${nacos.namespace}
      group: ${nacos.discovery.group}
  # 元数据中心
  metadata-report:
    address: nacos://${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
    parameters:
      namespace: ${nacos.namespace}-extra
  # 消费者相关配置
  consumer:
    # 支持校验注解
    validation: false
    # 超时时间
    timeout: 10000
    # 初始化检查
    check: false
  scan:
    # 接口实现类扫描
    base-packages: com.wd.**.api
