# nacos配置
nacos:
  server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  username: ${NACOS_USERNAME:nacos}
  password: ${NACOS_PASSWORD:nacos}
  namespace: ${NACOS_NAMESPACE:wd-cloud}
  config:
    group: ${NACOS_CONFIG_GROUP:server}
  discovery:
    group: ${NACOS_DISCOVERY_GROUP:public}
    cluster-name: ${NACOS_DISCOVERY_CLUSTER:master}


spring:
  application:
    name: ${APPLICATION_NAME:job-admin-server}
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.config.group}
        file-extension: yml
        auto-refresh: true
        bootstrap:
          enable: true
          log-enable: true
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.discovery.group}
        cluster-name: ${nacos.discovery.cluster-name}
  config:
    import:
      - nacos:job-admin-server
      - optional:nacos:common?group=common&refreshEnabled=true
