# nacos配置
nacos:
  server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  username: ${NACOS_USERNAME:nacos}
  password: ${NACOS_PASSWORD:nacos}
  namespace: ${NACOS_NAMESPACE:dev-namespace}
  config:
    group: ${NACOS_CONFIG_GROUP:SERVER}
  discovery:
    group: ${NACOS_DISCOVERY_GROUP:dev}
    cluster-name: ${NACOS_DISCOVERY_CLUSTER:master}

spring:
  application:
    name: ${APPLICATION_NAME:wd-demo}
  profiles:
    active: ${APPLICATION_PROFILE:dev}
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.config.group}
        file-extension: yml
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.discovery.group}
        cluster-name: ${nacos.discovery.cluster-name}
  config:
    import:
      - nacos:wd-demo.yml
      - optional:nacos:wd-common.yml?group=COMMON&refreshEnabled=true

